apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    USE mydb;
    CREATE TABLE IF NOT EXISTS hibernate_sequence (
                    next_val BIGINT NOT NULL
                );
    INSERT INTO hibernate_sequence (next_val)
                VALUES (1)
                ON DUPLICATE KEY UPDATE next_val = next_val;

    CREATE TABLE IF NOT EXISTS manager (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    name VARCHAR(255) UNIQUE,
                    password VARCHAR(255),
                    roles VARCHAR(255)
                );
    ALTER TABLE manager
                MODIFY COLUMN roles VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    CREATE TABLE IF NOT EXISTS employee (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    first_name VARCHAR(255) NOT NULL,
                    last_name VARCHAR(255) NOT NULL,
                    description TEXT,
                    manager_id BIGINT,
                    CONSTRAINT FK_manager FOREIGN KEY (manager_id) REFERENCES manager(id)
                );
    CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY 'mypassword';
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'rootpassword';
    GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'%' IDENTIFIED BY 'mypassword';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

    FLUSH PRIVILEGES;
